imports:
  - { resource: doctrine.yml, class: Symfony\Components\DependencyInjection\Loader\YamlFileLoader }
  - { resource: twig.yml, class: Symfony\Components\DependencyInjection\Loader\YamlFileLoader }

parameters:
  csrf_token.secret: secret

services:
  request:
    class: Symfony\Components\HttpKernel\Request
  response:
    class: Symfony\Components\HttpKernel\Response
  session:
    class: Symfony\Framework\WebBundle\Session\NativeSession
    arguments: [{ session_name: MODCASTS_SESSION }]
  csrf_token_factory:
    class: Modcasts\CSRFTokenFactory
    arguments: [%csrf_token.secret%]
