parameters:

services:
  twig: @twig.environment
  twig.environment:
    class: Twig_Environment
    arguments: [@twig.loader, { cache: cache/twig, debug: true }]
    calls:
      - [addExtension, [@twig.extension]]
  twig.loader:
    class: Twig_Loader_Filesystem
    arguments: [app/view]
  twig.extension:
    class: Modcasts\TwigExtension
